services:
  spiceapi:
    image: ${DOCKER_REGISTRY-}spiceapi
    restart: always
    build:
      context: .
      dockerfile: spiceapi/Dockerfile
    environment:
      DB_PASS: ajh4pDmG7QuzLZ9tH5sJn1KlA2I6eV3W8yBvXoNrPfTqYcRiSgE0wMxO7F1dU9
      DB_HOST: db
      DB_USER: postgres
      DB_NAME: db
      CRYPT_COST: "14"
    ports:
      - "8080:8080"
      - "8081:8081"
      - "8085:5150"
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ajh4pDmG7QuzLZ9tH5sJn1KlA2I6eV3W8yBvXoNrPfTqYcRiSgE0wMxO7F1dU9
      POSTGRES_DB: db
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - app-network

  spicehub:
    image: ${DOCKER_REGISTRY-}spicehub
    restart: always
    build:
      context: .
      dockerfile: spicehub/Dockerfile
    environment:
      BACKEND: http://localhost:8080
    ports:
      - "80:3000"
    depends_on:
      - spiceapi
    networks:
      - app-network


volumes:
  db-data:
    driver: local

networks:
  app-network:
    driver: bridge